### ISSUE TITLE
TypeError: pad() missing 1 required positional argument

### ISSUE THREAD

**Issue by mchimenti** [esalkovic/outsingle#4]
Error: 

> Sigma unknown:
> *************
> approximated coefficent w(beta):  1.6342634262627729
> optimal coefficent w(beta):  1.6405661661708708
> cutoff value:  31.44161666159435
> target rank:  17
> Traceback (most recent call last):
>   File "optht_svd_zs.py", line 82, in <module>
>     main()
>   File "optht_svd_zs.py", line 32, in main
>     process(data_file)
>   File "optht_svd_zs.py", line 57, in process
>     data_new = svd(data, U, s, VT, s_dimension)
>   File "optht_svd_zs.py", line 22, in svd
>     S = scipy.linalg.diagsvd(np.pad(s[:s_dimension], (0, len(s) - s_dimension)), *data.shape)
> TypeError: pad() missing 1 required positional argument: 'mode'

Call: 

> python optht_svd_zs.py test_gene_matrix-fzse-zs.csv

Related github error in other code: 

**https://github.com/NVlabs/instant-ngp/issues/557**

> Yeah pip install numpy --upgrade solved my problem.

Environment: 

> 
>      active environment : outsingle
>     active env location : /Users/mchiment/miniconda3/envs/outsingle
>             shell level : 3
>        user config file : /Users/mchiment/.condarc
>  populated config files : /Users/mchiment/.condarc
>           conda version : 24.1.2
>     conda-build version : not installed
>          python version : 3.12.1.final.0
>                  solver : libmamba (default)
>        virtual packages : __archspec=1=cascadelake
>                           __conda=24.1.2=0
>                           __glibc=2.17=0
>                           __linux=3.10.0=0
>                           __unix=0=0
>        base environment : /Users/mchiment/miniconda3  (writable)
>       conda av data dir : /Users/mchiment/miniconda3/etc/conda
>   conda av metadata url : None
>            channel URLs : https://conda.anaconda.org/biobakery/linux-64
>                           https://conda.anaconda.org/biobakery/noarch
>                           https://conda.anaconda.org/bioconda/linux-64
>                           https://conda.anaconda.org/bioconda/noarch
>                           https://conda.anaconda.org/conda-forge/linux-64
>                           https://conda.anaconda.org/conda-forge/noarch
>                           https://repo.anaconda.com/pkgs/main/linux-64
>                           https://repo.anaconda.com/pkgs/main/noarch
>                           https://repo.anaconda.com/pkgs/r/linux-64
>                           https://repo.anaconda.com/pkgs/r/noarch
>                           https://conda.anaconda.org/r/linux-64
>                           https://conda.anaconda.org/r/noarch
>           package cache : /Users/mchiment/miniconda3/pkgs
>                           /Users/mchiment/.conda/pkgs
>        envs directories : /Users/mchiment/miniconda3/envs
>                           /Users/mchiment/.conda/envs
>                platform : linux-64
>              user-agent : conda/24.1.2 requests/2.31.0 CPython/3.12.1 Linux/3.10.0-1160.83.1.el7.x86_64 centos/7.9.2009 glibc/2.17 solver/libmamba conda-libmamba-solver/23.12.0 libmambapy/1.5.3
>                 UID:GID : 1294132:900031646
>              netrc file : None
>            offline mode : False
>

**Comment by mchimenti** [comment]
Solution was to update environment to python 3.12 and numpy 1.26
